### ISSUE TITLE
Get field-specific search working

### ISSUE THREAD

**Issue by tmcdev** [Trott/ltdl3-client#25]
Hook it up so that searching a specific field will really and truly search across that field. As in, if the user selects Person from the first dropdown menu, the Person field (doc.per) will be the only field searched for that Search Row.

![clip](https://cloud.githubusercontent.com/assets/1381083/2897081/31bda4de-d578-11e3-8a4e-c5e12c7aaba5.png)
- Everything = _search across all fields_
- Title = doc.ti
- Person = doc.per
- Organization = doc.org
- Type = doc.dt
- Brand Name = doc.brd
- Bates Number = doc.bn
- ID Number = doc.id
- Text = doc.ot
- Metadata = doc.md
- Keyword = doc.kw
- Notes = doc.notes

**Comment by Trott** [comment]
This is bringing up a related issue that may not seem related from the outside, but here it is: What characters do we want to restrict searching on? Like, if you put punctuation in a Google query, it ignores it. I want to do the same thing so that people don't get weird unexpected results when they put in punctuation that has special meaning to Solr or Blacklight or whatever.

So what are the characters that I should allow in a query string? Alphabetic only? Alphanumeric? 

I realize that in the advanced/expert search, special characters will actually mean things. (E.g., the colon is the delimiter between a field and the value you're looking for in that field, or something like that.)

But in the simple search builder, what should we restrict it to?

/cc @tuolumne @rebeccatang @gboushey

**Comment by rebeccatang** [comment]
No need to process search text (in most cases).  Solr will take care of stripping out punctuations/special characters.

There are some special cases where search text need to be processed (highlighting non-text fields like dates and pages and wildcard in phrase queries), but we don't need to worry about them right now.

**Comment by Trott** [comment]
I'd still prefer to have a set of chars that I limit things to in order to reduce the likelihood of XSS shenanigans. But if there's no technical limitation, than this becomes a user experience question, so I'll wait for Tab to weigh in.

**Comment by tmcdev** [comment]
Clarification: the search builder will also accept advanced search characters like *, ~, :, ?, (, and ). Aside from that, I don't want to be throwing errors whenever the user types in a funky character; let the default Solr behavior stand and have the box strip out unnecessary junk a lá Google.

**Comment by Trott** [comment]
Is there a complete set of chars with special meaning?  `*`, `~`, `?`, `:`, `(`, `)`. Anything else? I feel like a pest asking, but I imagine we'll have to document it for users anyway.

**Comment by tuolumne** [comment]
It depends on what a user should be able to do. If a user is allowed to
specify range queries then we will also have to allow curly and angle
brackets.

**Comment by rebeccatang** [comment]
"+ - && || ! ( ) { } [ ] ^ " ~ \* ? : \"

http://lucene.apache.org/core/3_6_0/queryparsersyntax.html#Escaping%20Special%20Characters

**Comment by tmcdev** [comment]
Yep, that.

**Comment by Trott** [comment]
OK, field-specific search is working and is up on the demo site!
